# Generated by Django 2.2.2 on 2019-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crepe_nom', models.CharField(max_length=150, unique=True)),
                ('crepe_prix', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
